# Generated by Django 2.0 on 2019-07-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('dob', models.DateTimeField(auto_now_add=True)),
                ('admin_no', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=10)),
            ],
        ),
    ]
