# Generated by Django 2.0 on 2019-07-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190718_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_info',
            old_name='dob',
            new_name='date_birth',
        ),
    ]
