# Generated by Django 2.0 on 2019-07-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20190718_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='second_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
